create table book
(
    id             bigint generated by default as identity,
    title          varchar(255) not null,
    external_id    varchar(255) not null unique,
    isbn13         varchar(255),
    cover_url      varchar(255),
    published_year integer,
    description    varchar(20000),
    constraint pk_book primary key (id)
);

create table book_authors
(
    book_id bigint       not null,
    authors varchar(255) not null,
    constraint fk_book_authors_book foreign key (book_id) references book (id)
);

create table library_entry
(
    id         bigint generated by default as identity,
    book_id    bigint                   not null unique,
    status     varchar(20)              not null,
    rating     integer,
    notes      varchar(20000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint pk_library_entry primary key (id),
    constraint fk_library_entry_book foreign key (book_id) references book (id),
    constraint chk_library_entry_rating check ( rating between 1 and 5),
    constraint chk_library_entry_status check ( status in ('WANT_TO_READ', 'READING', 'READ'))
);